parameters:
#    ilis_users.example.class: Ilis\UsersBundle\Example

services:
#    ilis_users.example:
#        class: %ilis_users.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
