parameters:
#    ilis_forum.example.class: Ilis\ForumBundle\Example

services:
#    ilis_forum.example:
#        class: %ilis_forum.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
